name: Upload DLL Zip Artifact

on:
  push:
    branches:
      - main  # or master if your default branch is master

jobs:
  upload-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2  # This pulls your repository files

    - name: Create zip with DLL only
      run: zip -r dll-zip reboot.dll  # This zips only the .dll file

    - name: Upload zip as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dll-zip  # Artifact name
        path: dll-zip.zip  # Uploads the .zip file containing only the .dll
