name: Upload DLL Zip Artifact

on:
  push:
    branches:
      - main  # Change this to "master" if needed

jobs:
  upload-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2

    - name: Upload zip file
      uses: actions/upload-artifact@v3
      with:
        name: dll-zip  # Make sure the name is simple for Nightly.link
        path: "dll's-20240918T023443Z-001.zip"  # The exact path of your file
