name: Upload DLL Zip Artifact

on:
  push:
    branches:
      - main  # or "master" if that's your default branch

jobs:
  upload-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2  # Pulls your repository

    - name: Create zip with all DLLs
      run: zip -r dll-zip.zip Fortnite_Console_v2.2.dll Project_Reboot_3.0.dll craniumv2_1.dll  # Add the DLLs to the zip

    - name: Upload zip as artifact
      uses: actions/upload-artifact@v3
      with:
        name: dll-zip  # Name of the artifact
        path: dll-zip.zip  # Path to the zip file that was just created

