name: Upload Pre-existing DLL Zip

on:
  push:
    branches:
      - main  # Change to "master" if that's your default branch

jobs:
  upload-dll-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v2  # This pulls your repository code, including your zip file

    - name: Upload dll zip as artifact
      uses: actions/upload-artifact@v3  # Updated to v3 to avoid the deprecation error
      with:
        name: dll-zip-artifact  # You can change this name if you like
        path: "dll's-20240918T023443Z-001.zip"  # This is the zip file you uploaded
